version: '3.8'

services:
  flask_admin:
    build:
      context: ./services/flask_admin
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    volumes:
      - static_volume:/usr/src/app/project/static
    expose:
      - 5000
    env_file:
      - ./.env.prod
    depends_on:
      - db
      
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  nginx:
    build: ./services/nginx
    volumes:
      - static_volume:/usr/src/app/project/static
    ports:
      - 1337:80
    depends_on:
      - flask_admin

volumes:
  postgres_data_prod:
  static_volume:
